project_name: geomap
version: 2
builds:
  - id: geomap
    main: ./cmd/geomap
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w
    binary: geomap
archives:
  - id: archive
    builds:
      - geomap
    format_overrides:
      - goos: windows
        format: zip
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
checksum:
  name_template: 'checksums.txt'
changelog:
  use: git
release:
  draft: false
  prerelease: auto
